// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KS.RustAnalyzer
{
    internal sealed partial class Vsix
    {
        public const string Id = "KS.RustAnalyzer.86e60933-e1fd-4db1-992e-79303efc192b";
        public const string Name = "rust-analyzer";
        public const string Description = @"Rust language support for Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Kitam Studios";
        public const string Tags = "Rust;Cargo;RustAnalyser";
    }
}
