<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies Condition="'$(RaVsProjectOutputRoot)' != ''">true</CopyLocalLockFileAssemblies>
    <CopyDebugSymbolFilesFromPackages Condition="'$(RaVsProjectOutputRoot)' != ''">true</CopyDebugSymbolFilesFromPackages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\RustAnalyzer\source.extension.cs" Link="source.extension.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.12.0" ExcludeAssets="runtime" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" ExcludeAssets="runtime" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
  </ItemGroup>

  <Import Project="..\KS.Common.targets" />

</Project>
