<Project>
  <PropertyGroup>
    <AssemblySearchPath_UseAssemblyFoldersConfigFileSearchPath>false</AssemblySearchPath_UseAssemblyFoldersConfigFileSearchPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RaVsProjectOutputRoot)' != ''">
    <OutDir>$([MSBuild]::EnsureTrailingSlash('$(RaVsProjectOutputRoot)'))$(MSBuildProjectName)\</OutDir>
  </PropertyGroup>
</Project>
